# Generated by Django 4.1.1 on 2022-09-10 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Brand')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('payment', models.CharField(choices=[('Dtf', 'Datafono'), ('Etv', 'Efectivo'), ('Tsc', 'Transaccion')], default='Etv', max_length=11, verbose_name='Método de Pago')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Nombre', max_length=50, verbose_name='Nombre')),
                ('status', models.BooleanField(db_column='Estado', default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('image', models.ImageField(default='subcategory/Logo.png', null=True, upload_to='subcategory', verbose_name='Subcategoría')),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de Venta')),
                ('typeSale', models.CharField(choices=[('store', 'Local'), ('Domicilio', 'Domiclio')], default='store', max_length=9, verbose_name='Tipo de Venta')),
                ('finalPrice', models.IntegerField(default=0)),
                ('payment', models.CharField(choices=[('Dtf', 'Datafono'), ('Etv', 'Efectivo'), ('Tsc', 'Transaccion')], default='Etv', max_length=11, verbose_name='Método de Pago')),
                ('status', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.user', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Descripción')),
                ('expirationDate', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de Vencimiento')),
                ('unitMeasurement', models.CharField(choices=[('unit', 'Unidad'), ('pound', 'Lb'), ('kilogram', 'Kg')], default='unit', max_length=30, verbose_name='Unidad de medida')),
                ('stock', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(null=True, upload_to='product', verbose_name='Producto')),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.brand', verbose_name='Marca')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.subcategory', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('finalPrice', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product', verbose_name='Productos')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.sale', verbose_name='Id Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalle de ventas',
            },
        ),
        migrations.CreateModel(
            name='DetailBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.BooleanField(default=True)),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.buy', verbose_name='Id Compra')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalle de compras',
            },
        ),
        migrations.AddField(
            model_name='buy',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.provider', verbose_name='Proveedor'),
        ),
    ]
