# Generated by Django 4.1.1 on 2022-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='Nombre', max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
