# Generated by Django 4.1.1 on 2022-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='carrito/Logo.png', null=True, upload_to='carrito'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='subcategory/Logo.png', null=True, upload_to='subcategory'),
        ),
    ]
