# Generated by Django 4.0.4 on 2022-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsale',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Venta'),
        ),
    ]
