# Generated by Django 4.0.3 on 2022-09-15 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock'),
        ),
    ]
