# Generated by Django 4.0.4 on 2022-09-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_detailsale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsale',
            name='date',
        ),
    ]
