# Generated by Django 4.0.3 on 2022-09-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitMeasurement',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Libra', 'Lb'), ('Kilogramo', 'Kg'), ('Litro', 'L')], default='Unidad', max_length=30, verbose_name='Unidad de medida'),
        ),
    ]
