# Generated by Django 4.1.1 on 2022-09-11 20:15

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Copia de Seguridad', max_length=200)),
                ('file', models.FileField(upload_to='backup', validators=[management.models.validateExtent])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Copia de Seguridad',
                'verbose_name_plural': 'Copias de Seguridad',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='detailsale',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/Logo.png', null=True, upload_to='product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategory', verbose_name='Subcategoría'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
